### ISSUE TITLE
知乎屏蔽登录弹窗 按ESC键知乎会报错

### ISSUE THREAD

**Issue by asuper0** [yzx9/Tampermonkey#2]

**Comment by yzx9** [comment]
The escape event tries to remove the modal dom, but it has been removed by our script, so an exception is thrown:

```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

**Comment by asuper0** [comment]
更新后，问题还是存在，我的浏览器是Edge  105.0.1343.42 (正式版本) (64 位)

**Comment by yzx9** [comment]
@asuper0  Now that it's working properly for me now, can you provide more information? such as console error messages.

**Comment by asuper0** [comment]
[测试的页面](https://zhuanlan.zhihu.com/p/45566448)

![image](https://user-images.githubusercontent.com/41113804/192927877-7dc0ead6-a88a-4bf1-877c-bc9d9a276299.png)

以上是页面打开时的控制台，下面是按了ESC以后的

![image](https://user-images.githubusercontent.com/41113804/192927984-7bc6ea70-7db5-415e-aed8-06837325784c.png)

知乎的报错页面：
![image](https://user-images.githubusercontent.com/41113804/192928053-9e90ae13-bc83-40d6-b9ce-53a55130a5d7.png)

控制台的完整日志：
[zhuanlan.zhihu.com-1664420077026.log](https://github.com/yzx9/Tampermonkey/files/9670448/zhuanlan.zhihu.com-1664420077026.log)

奇怪的是，我这台电脑上分别用edge和chrome浏览器测试，都报错，另一台电脑使用是正常的

**Comment by yzx9** [comment]
Log 中有两个错误，第一个错误是因为测试页面不存在 `header.AppHeader` 导致，已修复（[bc6124e](https://github.com/yzx9/Tampermonkey/commit/bc6124ea42d6951d28161e96821648a9c847096a)），第二个错误是之前的 Esc 键导致，未能复现并且在 [6926a15](https://github.com/yzx9/Tampermonkey/commit/6926a1513ae919220b39754d7d08d65579aa4b88) 已经屏蔽了 Esc 键。

**Comment by yzx9** [comment]
[6926a15](https://github.com/yzx9/Tampermonkey/commit/6926a1513ae919220b39754d7d08d65579aa4b88)未能生效的原因可能是报错导致后续代码没执行，[e185fd6](https://github.com/yzx9/Tampermonkey/commit/e185fd6e346e004aa34c728afb330087c0f07c1d)中将屏蔽代码提前了，应该可以避免这一问题

**Comment by asuper0** [comment]
现在使用已经正常了👍
